nucleotides = input("Введите последовательность нуклеотидов: ")
def nucleotid_count(nucleotide, seq):
    seq = seq.upper()
    nucleotide = nucleotide.upper()
    return seq.count(nucleotide)
a_count = nucleotid_count("a", nucleotides)
t_count = nucleotid_count("t", nucleotides)
g_count = nucleotid_count("g", nucleotides)
c_count = nucleotid_count("c", nucleotides)
print(f"===Анализ последовательности ДНК===\n")
print(f'последовательность в верхнем регистре: {nucleotides.upper()}\n')
print(f'Подсчет нуклеотидов:\n')
print(f'A: {a_count}; % = {a_count/len(nucleotides)}\n')
print(f'T: {t_count}; % = {t_count/len(nucleotides)}\n')
print(f'G: {g_count}; % = {g_count/len(nucleotides)}\n')
print(f'C: {c_count}; % = {c_count/len(nucleotides)}\n')
print(f'Общая длина последовательности: {len(nucleotides)}\n')
